In [1]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv('by-state-0430.csv', index_col='date')

In [8]:
df.head()

,state,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,onVentilatorCumulative,...,hospitalized,total,totalTestResults,posNeg,fips,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease
date,,,,,,,,,,,,,,,,,,,,,
20200430,AK,355.0,18764.0,NaN,19.0,NaN,NaN,NaN,NaN,NaN,...,NaN,19119.0,19119.0,19119.0,2,0.0,0.0,0.0,0.0,0.0
20200430,AL,7019.0,80177.0,NaN,NaN,978.0,NaN,335.0,NaN,195.0,...,978.0,87196.0,87196.0,87196.0,1,24.0,33.0,6570.0,177.0,6747.0
20200430,AR,3255.0,45124.0,NaN,95.0,402.0,NaN,NaN,23.0,85.0,...,402.0,48379.0,48379.0,48379.0,5,2.0,13.0,2867.0,63.0,2930.0
20200430,AS,0.0,3.0,17.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,20.0,3.0,3.0,60,0.0,0.0,0.0,0.0,0.0
20200430,AZ,7648.0,64138.0,NaN,755.0,1169.0,311.0,NaN,194.0,NaN,...,1169.0,71786.0,71786.0,71786.0,4,16.0,38.0,2527.0,446.0,2973.0

In [9]:
df.index = pd.to_datetime(df.index)

In [10]:
df

,state,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,onVentilatorCumulative,...,hospitalized,total,totalTestResults,posNeg,fips,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease
date,,,,,,,,,,,,,,,,,,,,,
1970-01-01 00:00:00.020200430,AK,355.0,18764.0,NaN,19.0,NaN,NaN,NaN,NaN,NaN,...,NaN,19119.0,19119.0,19119.0,2,0.0,0.0,0.0,0.0,0.0
1970-01-01 00:00:00.020200430,AL,7019.0,80177.0,NaN,NaN,978.0,NaN,335.0,NaN,195.0,...,978.0,87196.0,87196.0,87196.0,1,24.0,33.0,6570.0,177.0,6747.0
1970-01-01 00:00:00.020200430,AR,3255.0,45124.0,NaN,95.0,402.0,NaN,NaN,23.0,85.0,...,402.0,48379.0,48379.0,48379.0,5,2.0,13.0,2867.0,63.0,2930.0
1970-01-01 00:00:00.020200430,AS,0.0,3.0,17.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,20.0,3.0,3.0,60,0.0,0.0,0.0,0.0,0.0
1970-01-01 00:00:00.020200430,AZ,7648.0,64138.0,NaN,755.0,1169.0,311.0,NaN,194.0,NaN,...,1169.0,71786.0,71786.0,71786.0,4,16.0,38.0,2527.0,446.0,2973.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1970-01-01 00:00:00.020200126,WA,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,1.0,1.0,53,0.0,0.0,0.0,0.0,0.0
1970-01-01 00:00:00.020200125,WA,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,1.0,1.0,53,0.0,0.0,0.0,0.0,0.0
1970-01-01 00:00:00.020200124,WA,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,1.0,1.0,53,0.0,0.0,0.0,0.0,0.0
1970-01-01 00:00:00.020200123,WA,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,1.0,1.0,53,0.0,0.0,0.0,0.0,0.0
1970-01-01 00:00:00.020200122,WA,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,1.0,1.0,53,NaN,NaN,NaN,NaN,NaN